const T={
en:{
"nav.about":"About","nav.skills":"Skills","nav.experience":"Experience","nav.projects":"Projects","nav.contact":"Contact","nav.letsTalk":"Let's talk","skip":"Skip to content",
"hero.eyebrow":"Full-Stack Web Developer · Open to opportunities","hero.location":"Taza, Morocco · Open to relocation","hero.title":"I build web applications that are <em>useful, tested, and built to last.</em>","hero.lede":"Full-Stack Web Developer with hands-on experience building Laravel, PHP, MySQL, React.js and Node.js applications, with a strong focus on backend development, RESTful APIs and application testing.","hero.projects":"View my projects ↗","hero.resume":"Download resume",
"proof.experience":"professional experiences","proof.projects":"projects","proof.education":"education milestones","proof.stack":"technologies & tools","proof.languages":"portfolio languages",
"about.kicker":"ABOUT ME","about.title":"From backend logic to <em>clean interfaces.</em>","about.p1":"I’m a Full-Stack Web Developer focused on building database-driven web applications and reliable backend systems.","about.p2":"My experience spans Laravel and PHP backend development, React.js frontend integration, RESTful APIs, MySQL and MongoDB, plus automated testing and debugging workflows.","about.p3":"I enjoy turning requirements into clear features, connecting frontend and backend systems, and validating applications with disciplined testing.",
"skills.kicker":"TECHNICAL STACK","skills.title":"Tools I use to <em>build and verify.</em>","skills.intro":"A practical stack covering frontend, backend, APIs, databases, testing and delivery.","skills.frontend":"Frontend","skills.backend":"Backend","skills.data":"Data & APIs","skills.testing":"Testing","skills.tools":"Tools & delivery","skills.methods":"Methodologies",
"exp.kicker":"EXPERIENCE","exp.title":"Building, testing, and <em>debugging real systems.</em>","exp.rakops":"Designed automated test suites from scratch for Laravel and React.js applications, covering functional, E2E, regression and edge-case scenarios. Tested APIs, authentication, authorization, forms, databases and security with Postman and OWASP ZAP.","exp.freelance":"Developed a company profile web application with Laravel and React.js, including backend functionality, frontend integration and a content management dashboard.","exp.dpg":"Developed backend features with Laravel, PHP, MySQL and Node.js, implementing server-side functionality and database operations according to project requirements.","exp.anef":"Developed a full-stack web application for managing payment slips, with features for creating, managing and tracking payment-slip records and database-driven user interfaces.",
"projects.kicker":"SELECTED BUILDS","projects.title":"Work that connects <em>features to systems.</em>","projects.intro":"These are portfolio-ready presentations of work explicitly supported by my experience. No invented metrics or technologies.","proj.monitoring.title":"Website Audit & Monitoring Platform","proj.monitoring.desc":"An audit and monitoring platform that continuously checks websites through a broad set of tools, inspired by the workflow of products such as Semrush.","proj.monitoring.contribution":"Fixed bugs, created the login system and user roles, wrote PHPUnit feature tests, helped ensure the application worked reliably, and built the monitoring system with around 30 supporting tools.","proj.company.title":"Company Profile Web Application","proj.company.desc":"A company profile web application built with Laravel and React.js, combining backend functionality with frontend integration and a content management dashboard.","proj.company.contribution":"Backend functionality, frontend integration, content management and feature testing.","proj.payments.title":"Payment Slip Management Application","proj.payments.desc":"A full-stack web application developed for managing payment slips, including creation, management and tracking of payment-slip records.","proj.payments.contribution":"Application functionality, database-driven features and user interfaces aligned with organizational requirements.","proj.testing.title":"Automated Testing Suite","proj.testing.desc":"Automated test suites created for Laravel and React.js applications, covering functional, E2E, regression and edge-case scenarios.","proj.testing.contribution":"Test design, API/security validation, bug reproduction, fix verification and ongoing test maintenance.","proj.role":"Contribution","ui.records":"PAYMENT RECORDS","ui.audit":"AUDIT & MONITORING","ui.monitorTools":"monitoring tools","ui.authentication":"Authentication","ui.roles":"Roles","ui.monitoring":"Monitoring",
"edu.kicker":"EDUCATION","edu.title":"A foundation in <em>software engineering.</em>","edu.ensa":"Professional Diploma in Software Engineering and Information Systems · Kenitra, Morocco","edu.ofppt":"Specialized Technician in Digital Development (Full Stack Development) · Taza, Morocco","edu.bac":"Baccalaureate in Physical and Chemical Sciences · Taza, Morocco",
"contact.kicker":"LET'S CONNECT","contact.title":"Have a project or role in mind? <em>Let's talk.</em>","contact.intro":"I’m open to Full-Stack and Backend Developer opportunities. Send a message and I’ll get back to you.",
"form.name":"Name","form.email":"Email","form.subject":"Subject","form.message":"Message","form.namePh":"Your name","form.emailPh":"you@example.com","form.subjectPh":"How can I help?","form.messagePh":"Tell me a little about your project or opportunity...","form.send":"Send message ↗",
"footer.top":"Back to top ↑","resume.kicker":"RESUME","resume.title":"Choose a language","resume.intro":"English is available now. Add the other PDF files to the resume folder when ready."
},
fr:{
"nav.about":"À propos","nav.skills":"Compétences","nav.experience":"Expérience","nav.projects":"Projets","nav.contact":"Contact","nav.letsTalk":"Parlons-en","skip":"Aller au contenu",
"hero.eyebrow":"Développeur Web Full-Stack · Ouvert aux opportunités","hero.location":"Taza, Maroc · Ouvert à la mobilité","hero.title":"Je construis des applications web <em>utiles, testées et durables.</em>","hero.lede":"Développeur Web Full-Stack avec une expérience pratique en Laravel, PHP, MySQL, React.js et Node.js, avec un fort intérêt pour le backend, les API REST et les tests applicatifs.","hero.projects":"Voir mes projets ↗","hero.resume":"Télécharger le CV",
"proof.experience":"expériences professionnelles","proof.projects":"projets","proof.education":"étapes de formation","proof.stack":"technologies & outils","proof.languages":"langues du portfolio",
"about.kicker":"À PROPOS","about.title":"De la logique backend aux <em>interfaces claires.</em>","about.p1":"Je suis Développeur Web Full-Stack, spécialisé dans les applications web pilotées par les données et les systèmes backend fiables.","about.p2":"Mon expérience couvre le développement backend avec Laravel et PHP, l’intégration frontend avec React.js, les API REST, MySQL et MongoDB, ainsi que les tests automatisés et le débogage.","about.p3":"J’aime transformer les besoins en fonctionnalités claires, connecter frontend et backend et valider les applications avec une démarche de test rigoureuse.",
"skills.kicker":"STACK TECHNIQUE","skills.title":"Les outils que j’utilise pour <em>construire et vérifier.</em>","skills.intro":"Une stack pratique couvrant frontend, backend, API, bases de données, tests et livraison.","skills.frontend":"Frontend","skills.backend":"Backend","skills.data":"Données & API","skills.testing":"Tests","skills.tools":"Outils & livraison","skills.methods":"Méthodologies",
"exp.kicker":"EXPÉRIENCE","exp.title":"Construire, tester et <em>déboguer des systèmes réels.</em>","exp.rakops":"Conception de suites de tests automatisés pour des applications Laravel et React.js, couvrant les scénarios fonctionnels, E2E, de régression et les cas limites. Tests d’API, d’authentification, d’autorisation, de formulaires, de bases de données et de sécurité avec Postman et OWASP ZAP.","exp.freelance":"Développement d’une application web de présentation d’entreprise avec Laravel et React.js, incluant le backend, l’intégration frontend et un tableau de bord de gestion de contenu.","exp.dpg":"Développement de fonctionnalités backend avec Laravel, PHP, MySQL et Node.js, avec implémentation de fonctionnalités serveur et d’opérations sur les bases de données.","exp.anef":"Développement d’une application web full-stack de gestion des bordereaux de paiement, avec création, gestion et suivi des enregistrements et des interfaces pilotées par la base de données.",
"projects.kicker":"RÉALISATIONS","projects.title":"Des réalisations qui relient <em>fonctionnalités et systèmes.</em>","projects.intro":"Des présentations basées uniquement sur les travaux explicitement présents dans mon expérience. Aucun chiffre ni outil inventé.","proj.monitoring.title":"Plateforme d’Audit & de Monitoring Web","proj.monitoring.desc":"Une plateforme d’audit et de monitoring qui vérifie en continu les sites web grâce à un large ensemble d’outils, dans un flux de travail inspiré de produits comme Semrush.","proj.monitoring.contribution":"Correction de bugs, création du système de connexion et des rôles utilisateurs, rédaction de tests fonctionnels PHPUnit, vérification de la fiabilité de l’application et création du système de monitoring avec environ 30 outils.","proj.company.title":"Application Web de Présentation d’Entreprise","proj.company.desc":"Application web de présentation d’entreprise développée avec Laravel et React.js, combinant fonctionnalités backend, intégration frontend et tableau de bord de gestion de contenu.","proj.company.contribution":"Fonctionnalités backend, intégration frontend, gestion de contenu et tests de fonctionnalités.","proj.payments.title":"Application de Gestion des Bordereaux de Paiement","proj.payments.desc":"Application web full-stack développée pour gérer les bordereaux de paiement, avec création, gestion et suivi des enregistrements.","proj.payments.contribution":"Fonctionnalités applicatives, fonctionnalités pilotées par les données et interfaces selon les besoins de l’organisation.","proj.testing.title":"Suite de Tests Automatisés","proj.testing.desc":"Suites de tests automatisés créées pour des applications Laravel et React.js, couvrant les scénarios fonctionnels, E2E, de régression et les cas limites.","proj.testing.contribution":"Conception des tests, validation API/sécurité, reproduction des bugs, vérification des corrections et maintenance des tests.","proj.role":"Contribution","ui.records":"ENREGISTREMENTS DE PAIEMENT","ui.audit":"AUDIT & MONITORING","ui.monitorTools":"outils de monitoring","ui.authentication":"Authentification","ui.roles":"Rôles","ui.monitoring":"Monitoring",
"edu.kicker":"FORMATION","edu.title":"Une base solide en <em>ingénierie logicielle.</em>","edu.ensa":"Diplôme professionnel en Ingénierie Logicielle et Systèmes d’Information · Kénitra, Maroc","edu.ofppt":"Technicien Spécialisé en Développement Digital (Full Stack) · Taza, Maroc","edu.bac":"Baccalauréat Sciences Physiques et Chimiques · Taza, Maroc",
"contact.kicker":"CONTACT","contact.title":"Un projet ou un poste en tête ? <em>Parlons-en.</em>","contact.intro":"Je suis ouvert aux opportunités de Développeur Full-Stack et Backend. Envoyez-moi un message et je vous répondrai.",
"form.name":"Nom","form.email":"E-mail","form.subject":"Objet","form.message":"Message","form.namePh":"Votre nom","form.emailPh":"vous@exemple.com","form.subjectPh":"Comment puis-je vous aider ?","form.messagePh":"Parlez-moi de votre projet ou de votre opportunité...","form.send":"Envoyer le message ↗","footer.top":"Retour en haut ↑","resume.kicker":"CV","resume.title":"Choisissez une langue","resume.intro":"Le CV anglais est disponible. Ajoutez les autres PDF dans le dossier resume lorsqu’ils seront prêts."
},
es:{
"nav.about":"Sobre mí","nav.skills":"Habilidades","nav.experience":"Experiencia","nav.projects":"Proyectos","nav.contact":"Contacto","nav.letsTalk":"Hablemos","skip":"Ir al contenido",
"hero.eyebrow":"Desarrollador Web Full-Stack · Abierto a oportunidades","hero.location":"Taza, Marruecos · Disponible para reubicación","hero.title":"Construyo aplicaciones web <em>útiles, probadas y duraderas.</em>","hero.lede":"Desarrollador Web Full-Stack con experiencia práctica en Laravel, PHP, MySQL, React.js y Node.js, centrado en backend, APIs REST y pruebas de aplicaciones.","hero.projects":"Ver mis proyectos ↗","hero.resume":"Descargar CV",
"proof.experience":"experiencias profesionales","proof.projects":"proyectos","proof.education":"etapas académicas","proof.stack":"tecnologías y herramientas","proof.languages":"idiomas del portfolio",
"about.kicker":"SOBRE MÍ","about.title":"De la lógica backend a <em>interfaces claras.</em>","about.p1":"Soy Desarrollador Web Full-Stack y me enfoco en aplicaciones web basadas en datos y sistemas backend fiables.","about.p2":"Mi experiencia incluye backend con Laravel y PHP, integración frontend con React.js, APIs REST, MySQL y MongoDB, además de pruebas automatizadas y depuración.","about.p3":"Me gusta convertir requisitos en funcionalidades claras, conectar frontend y backend y validar aplicaciones mediante pruebas rigurosas.",
"skills.kicker":"STACK TÉCNICO","skills.title":"Herramientas para <em>construir y verificar.</em>","skills.intro":"Un stack práctico para frontend, backend, APIs, bases de datos, pruebas y entrega.","skills.frontend":"Frontend","skills.backend":"Backend","skills.data":"Datos y APIs","skills.testing":"Pruebas","skills.tools":"Herramientas y entrega","skills.methods":"Metodologías",
"exp.kicker":"EXPERIENCIA","exp.title":"Construir, probar y <em>depurar sistemas reales.</em>","exp.rakops":"Diseñé suites de pruebas automatizadas desde cero para aplicaciones Laravel y React.js, cubriendo escenarios funcionales, E2E, regresión y casos límite. Probé APIs, autenticación, autorización, formularios, bases de datos y seguridad con Postman y OWASP ZAP.","exp.freelance":"Desarrollé una aplicación web de presentación de empresa con Laravel y React.js, incluyendo backend, integración frontend y un panel de gestión de contenido.","exp.dpg":"Desarrollé funcionalidades backend con Laravel, PHP, MySQL y Node.js, implementando lógica del servidor y operaciones de base de datos según los requisitos.","exp.anef":"Desarrollé una aplicación web full-stack para gestionar comprobantes de pago, con creación, gestión y seguimiento de registros e interfaces basadas en datos.",
"projects.kicker":"TRABAJOS SELECCIONADOS","projects.title":"Trabajo que conecta <em>funcionalidades y sistemas.</em>","projects.intro":"Presentaciones basadas únicamente en trabajos respaldados por mi experiencia. Sin métricas ni tecnologías inventadas.","proj.monitoring.title":"Plataforma de Auditoría y Monitorización Web","proj.monitoring.desc":"Una plataforma de auditoría y monitorización que comprueba continuamente sitios web mediante un amplio conjunto de herramientas, inspirada en el flujo de trabajo de productos como Semrush.","proj.monitoring.contribution":"Corrección de errores, creación del sistema de inicio de sesión y roles de usuario, escritura de pruebas funcionales con PHPUnit, verificación del correcto funcionamiento y creación del sistema de monitorización con unas 30 herramientas.","proj.company.title":"Aplicación Web de Perfil Empresarial","proj.company.desc":"Aplicación web de perfil empresarial desarrollada con Laravel y React.js, combinando backend, integración frontend y un panel de gestión de contenido.","proj.company.contribution":"Funcionalidad backend, integración frontend, gestión de contenido y pruebas de funcionalidades.","proj.payments.title":"Aplicación de Gestión de Comprobantes de Pago","proj.payments.desc":"Aplicación web full-stack para gestionar comprobantes de pago, incluyendo creación, gestión y seguimiento de registros.","proj.payments.contribution":"Funcionalidad de la aplicación, características basadas en base de datos e interfaces según los requisitos organizativos.","proj.testing.title":"Suite de Pruebas Automatizadas","proj.testing.desc":"Suites de pruebas automatizadas para aplicaciones Laravel y React.js, cubriendo escenarios funcionales, E2E, regresión y casos límite.","proj.testing.contribution":"Diseño de pruebas, validación de API/seguridad, reproducción de errores, verificación de correcciones y mantenimiento.","proj.role":"Contribución","ui.records":"REGISTROS DE PAGO","ui.audit":"AUDITORÍA Y MONITORIZACIÓN","ui.monitorTools":"herramientas de monitorización","ui.authentication":"Autenticación","ui.roles":"Roles","ui.monitoring":"Monitorización",
"edu.kicker":"FORMACIÓN","edu.title":"Una base en <em>ingeniería de software.</em>","edu.ensa":"Diploma Profesional en Ingeniería de Software y Sistemas de Información · Kenitra, Marruecos","edu.ofppt":"Técnico Especializado en Desarrollo Digital (Full Stack) · Taza, Marruecos","edu.bac":"Bachillerato en Ciencias Físicas y Químicas · Taza, Marruecos",
"contact.kicker":"CONTACTO","contact.title":"¿Tienes un proyecto o puesto en mente? <em>Hablemos.</em>","contact.intro":"Estoy abierto a oportunidades como Desarrollador Full-Stack o Backend. Envíame un mensaje y te responderé.",
"form.name":"Nombre","form.email":"Correo","form.subject":"Asunto","form.message":"Mensaje","form.namePh":"Tu nombre","form.emailPh":"tu@ejemplo.com","form.subjectPh":"¿Cómo puedo ayudarte?","form.messagePh":"Cuéntame sobre tu proyecto u oportunidad...","form.send":"Enviar mensaje ↗","footer.top":"Volver arriba ↑","resume.kicker":"CV","resume.title":"Elige un idioma","resume.intro":"El CV en inglés está disponible. Añade los otros PDF a la carpeta resume cuando estén listos."
},
de:{
"nav.about":"Über mich","nav.skills":"Skills","nav.experience":"Erfahrung","nav.projects":"Projekte","nav.contact":"Kontakt","nav.letsTalk":"Kontakt aufnehmen","skip":"Zum Inhalt",
"hero.eyebrow":"Full-Stack-Webentwickler · Offen für neue Möglichkeiten","hero.location":"Taza, Marokko · Offen für einen Umzug","hero.title":"Ich entwickle Webanwendungen, die <em>nützlich, getestet und langlebig sind.</em>","hero.lede":"Full-Stack-Webentwickler mit praktischer Erfahrung in Laravel, PHP, MySQL, React.js und Node.js, mit Fokus auf Backend-Entwicklung, RESTful APIs und Anwendungstests.","hero.projects":"Projekte ansehen ↗","hero.resume":"Lebenslauf herunterladen",
"proof.experience":"Berufserfahrungen","proof.projects":"Projekte","proof.education":"Ausbildungsstationen","proof.stack":"Technologien & Tools","proof.languages":"Portfolio-Sprachen",
"about.kicker":"ÜBER MICH","about.title":"Von Backend-Logik zu <em>klaren Interfaces.</em>","about.p1":"Ich bin Full-Stack-Webentwickler mit Fokus auf datenbankgestützte Webanwendungen und zuverlässige Backend-Systeme.","about.p2":"Meine Erfahrung umfasst Backend-Entwicklung mit Laravel und PHP, React.js-Integration, RESTful APIs, MySQL und MongoDB sowie automatisierte Tests und Debugging.","about.p3":"Ich übersetze Anforderungen gern in klare Funktionen, verbinde Frontend und Backend und validiere Anwendungen mit strukturierten Tests.",
"skills.kicker":"TECH-STACK","skills.title":"Werkzeuge zum <em>Entwickeln und Prüfen.</em>","skills.intro":"Ein praxisnaher Stack für Frontend, Backend, APIs, Datenbanken, Tests und Delivery.","skills.frontend":"Frontend","skills.backend":"Backend","skills.data":"Daten & APIs","skills.testing":"Tests","skills.tools":"Tools & Delivery","skills.methods":"Methoden",
"exp.kicker":"ERFAHRUNG","exp.title":"Entwickeln, testen und <em>reale Systeme debuggen.</em>","exp.rakops":"Automatisierte Testsuiten für Laravel- und React.js-Anwendungen von Grund auf entwickelt, mit funktionalen, E2E-, Regressions- und Edge-Case-Szenarien. APIs, Authentifizierung, Autorisierung, Formulare, Datenbanken und Sicherheit mit Postman und OWASP ZAP getestet.","exp.freelance":"Eine Unternehmensprofil-Webanwendung mit Laravel und React.js entwickelt, einschließlich Backend-Funktionen, Frontend-Integration und Content-Management-Dashboard.","exp.dpg":"Backend-Funktionen mit Laravel, PHP, MySQL und Node.js entwickelt sowie serverseitige Logik und Datenbankoperationen gemäß den Anforderungen umgesetzt.","exp.anef":"Eine Full-Stack-Webanwendung zur Verwaltung von Zahlungsbelegen entwickelt, einschließlich Erstellung, Verwaltung und Nachverfolgung von Datensätzen und datenbankgestützten Oberflächen.",
"projects.kicker":"AUSGEWÄHLTE BUILDS","projects.title":"Arbeiten, die <em>Funktionen mit Systemen verbinden.</em>","projects.intro":"Präsentationen von Arbeiten, die ausdrücklich durch meine Erfahrung belegt sind. Keine erfundenen Kennzahlen oder Technologien.","proj.monitoring.title":"Web-Audit- & Monitoring-Plattform","proj.monitoring.desc":"Eine Audit- und Monitoring-Plattform, die Websites kontinuierlich mit einer breiten Auswahl an Tools prüft – inspiriert von Workflows aus Produkten wie Semrush.","proj.monitoring.contribution":"Fehler behoben, Login-System und Benutzerrollen erstellt, PHPUnit-Feature-Tests geschrieben, die zuverlässige Funktion sichergestellt und das Monitoring-System mit rund 30 unterstützenden Tools entwickelt.","proj.company.title":"Webanwendung für ein Unternehmensprofil","proj.company.desc":"Eine mit Laravel und React.js entwickelte Unternehmensprofil-Webanwendung mit Backend-Funktionen, Frontend-Integration und Content-Management-Dashboard.","proj.company.contribution":"Backend-Funktionen, Frontend-Integration, Content-Management und Funktionstests.","proj.payments.title":"Anwendung zur Verwaltung von Zahlungsbelegen","proj.payments.desc":"Eine Full-Stack-Webanwendung zur Verwaltung von Zahlungsbelegen, einschließlich Erstellung, Verwaltung und Nachverfolgung von Datensätzen.","proj.payments.contribution":"Anwendungsfunktionen, datenbankgestützte Features und Oberflächen nach organisatorischen Anforderungen.","proj.testing.title":"Automatisierte Testsuite","proj.testing.desc":"Automatisierte Testsuiten für Laravel- und React.js-Anwendungen mit funktionalen, E2E-, Regressions- und Edge-Case-Szenarien.","proj.testing.contribution":"Testdesign, API-/Sicherheitsvalidierung, Fehlerreproduktion, Prüfung von Korrekturen und Testpflege.","proj.role":"Beitrag","ui.records":"ZAHLUNGSBELEGE","ui.audit":"AUDIT & MONITORING","ui.monitorTools":"Monitoring-Tools","ui.authentication":"Authentifizierung","ui.roles":"Rollen","ui.monitoring":"Monitoring",
"edu.kicker":"AUSBILDUNG","edu.title":"Grundlage in <em>Software Engineering.</em>","edu.ensa":"Berufsdiplom Software Engineering und Informationssysteme · Kenitra, Marokko","edu.ofppt":"Staatlich geprüfter Techniker für digitale Entwicklung (Full-Stack) · Taza, Marokko","edu.bac":"Abitur in Physik und Chemie · Taza, Marokko",
"contact.kicker":"KONTAKT","contact.title":"Du hast ein Projekt oder eine Stelle im Kopf? <em>Lass uns sprechen.</em>","contact.intro":"Ich bin offen für Full-Stack- und Backend-Entwicklerpositionen. Sende mir eine Nachricht und ich melde mich zurück.",
"form.name":"Name","form.email":"E-Mail","form.subject":"Betreff","form.message":"Nachricht","form.namePh":"Dein Name","form.emailPh":"du@beispiel.de","form.subjectPh":"Wie kann ich helfen?","form.messagePh":"Erzähl mir etwas über dein Projekt oder deine Gelegenheit...","form.send":"Nachricht senden ↗","footer.top":"Nach oben ↑","resume.kicker":"LEBENSLAUF","resume.title":"Sprache auswählen","resume.intro":"Der englische Lebenslauf ist verfügbar. Füge die anderen PDFs später in den Ordner resume ein."
}};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let lang=localStorage.getItem("portfolio-lang")||"en";
function applyLang(l){lang=T[l]?l:"en";document.documentElement.lang=lang;$$("[data-i18n]").forEach(e=>{let v=T[lang][e.dataset.i18n];if(v!==undefined)e.textContent=v});$$("[data-i18n-html]").forEach(e=>{let v=T[lang][e.dataset.i18nHtml];if(v!==undefined)e.innerHTML=v});$$("[data-i18n-placeholder]").forEach(e=>{let v=T[lang][e.dataset.i18nPlaceholder];if(v!==undefined)e.placeholder=v});$$("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));localStorage.setItem("portfolio-lang",lang)}
document.addEventListener("DOMContentLoaded",()=>{
applyLang(lang);$("#year").textContent=new Date().getFullYear();
$$("[data-lang]").forEach(b=>b.onclick=()=>applyLang(b.dataset.lang));
const header=$(".header");addEventListener("scroll",()=>header.classList.toggle("scrolled",scrollY>15),{passive:true});
$("#themeBtn").onclick=()=>{let d=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=d;localStorage.setItem("portfolio-theme",d)};
document.documentElement.dataset.theme=localStorage.getItem("portfolio-theme")||"dark";
$("#menuBtn").onclick=()=>{let open=header.classList.toggle("menu-open");$("#menuBtn").setAttribute("aria-expanded",open)};
$$(".mobile-nav a").forEach(a=>a.onclick=()=>header.classList.remove("menu-open"));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});$$(".reveal").forEach(e=>observer.observe(e));
const dlg=$("#resumeDialog");$("#resumeBtn").onclick=()=>dlg.showModal();$("#resumeClose").onclick=()=>dlg.close();dlg.addEventListener("click",e=>{if(e.target===dlg)dlg.close()});
$$("[data-future]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();alert("Add the translated PDF to resume/ using the filename shown in this option.")}));
$("#contactForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,status=$("#formStatus"),btn=$("#submitBtn");if(!form.checkValidity()){form.reportValidity();return}btn.disabled=true;status.textContent=lang==="fr"?"Envoi…":lang==="es"?"Enviando…":lang==="de"?"Wird gesendet…":"Sending…";try{const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});if(!r.ok)throw new Error();form.reset();status.textContent=lang==="fr"?"Message envoyé. Merci !":lang==="es"?"Mensaje enviado. ¡Gracias!":lang==="de"?"Nachricht gesendet. Danke!":"Message sent. Thank you!";}catch(_){status.textContent=lang==="fr"?"Impossible d’envoyer. Écrivez-moi directement par e-mail.":lang==="es"?"No se pudo enviar. Escríbeme directamente por correo.":lang==="de"?"Senden fehlgeschlagen. Bitte schreiben Sie mir direkt per E-Mail.":"Could not send. Please email me directly."}finally{btn.disabled=false}});
});
